name: Deploy to Netlify

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Generate secrets.js
      run: |
        echo "window.secrets = {" >> js/secrets.js
        echo "  API_KEY: '$API_KEY'," >> js/secrets.js
        echo "  EMAIL_JS: '$EMAIL_JS'," >> js/secrets.js
        echo "  SITE_KEY: '$SITE_KEY'" >> js/secrets.js
        echo "};" >> js/secrets.js

    - name: Move secrets.js to js directory
      run: mv js/secrets.js js/

    - name: Build and Deploy
      run: npm run build

    - name: Deploy to Netlify
      uses: netlify/actions/cli@master
      with:
        args: deploy --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETFLIFY_AUTH_TOKEN }}
